# Configuration for which validations to run for region US_MA.

region_code: US_MA
# TODO(#31854): Enable validations for US_MA.
dev_mode: True
exclusions:
  - validation_name: session_new_admissions_with_no_sentence_date_imposed
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason:
      Uniquely, MA has sessions but no ingested incarceration / supervision periods or sentences.
      Therefore, validations like this one can be disabled until meaningful ingest happens in MA.
  - validation_name: sessions_missing_closest_sentence_imposed_group
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason:
      Uniquely, MA has sessions but no ingested incarceration / supervision periods or sentences.
      Therefore, validations like this one can be disabled until meaningful ingest happens in MA.
  - validation_name: sessions_persons_in_incarceration_or_supervision
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason:
      Uniquely, MA has sessions but no ingested incarceration / supervision periods or sentences.
      Therefore, validations like this one can be disabled until meaningful ingest happens in MA.
  - validation_name: session_liberty_releases_with_no_sentence_completion_date
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason:
      Uniquely, MA has sessions but no ingested incarceration / supervision periods or sentences.
      Therefore, validations like this one can be disabled until meaningful ingest happens in MA.
  - validation_name: case_insights_rates_missing_charges
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: Sentencing assistance case insights are not configured/launched for this state
  - validation_name: person_caseload_location_sessions_caseload
    exclusion_type: BROKEN
    exclusion_reason:
      Validation is not working properly for the INCARCERATION compartment and
      is expected to fail for almost all rows until fixed.
      # TODO(#46520): Remove this exclusion once this validation has been fixed.
  - validation_name: person_caseload_location_sessions_location
    exclusion_type: BROKEN
    exclusion_reason:
      Validation is not working properly for the INCARCERATION compartment and
      is expected to fail for almost all rows until fixed.
      # TODO(#46520): Remove this exclusion once this validation has been fixed.
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
