terraform:
  # Describes where the Terraform state file for these centrally-managed components is stored
  # https://atmos.tools/core-concepts/components/terraform/backends#google-cloud-storage-backend
  backend_type: gcs
  backend:
    gcs:
      bucket: recidiviz-devops-tf-state
      prefix: "projects/{{ .settings.context.project_id }}/{{ .component }}"
  # This provides the default configuration for our Terraform providers
  # https://atmos.tools/core-concepts/components/terraform/providers
  providers:
    google:
      project: "{{ .settings.context.project_id }}"
    google-beta:
      project: "{{ .settings.context.project_id }}"
