# Configuration for which validations to run for region US_NC.

region_code: US_NC
# TODO(#34198): Enable validations for US_NC.
dev_mode: True
exclusions:
  - validation_name: case_insights_rates_missing_charges
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: Sentencing assistance case insights are not configured/launched for this state
  - validation_name: sessions_missing_closest_sentence_imposed_group
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: We don't have sentencing information in NC. TODO(#56006) if we do ingest sentences!
  - validation_name: session_new_admissions_with_no_sentence_date_imposed
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: We don't have sentencing information in NC. TODO(#56006) if we do ingest sentences!
max_allowed_error_overrides: []
num_allowed_rows_overrides: []
