# Configuration for which validations to run for region US_NC.

region_code: US_NC
# TODO(#34198): Enable validations for US_NC.
dev_mode: True
exclusions:
  - validation_name: case_insights_rates_missing_charges
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: Sentencing assistance case insights are not configured/launched for this state
  - validation_name: sessions_missing_closest_sentence_imposed_group
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: We don't have sentencing information in NC. TODO(#56006) if we do ingest sentences!
  - validation_name: session_new_admissions_with_no_sentence_date_imposed
    exclusion_type: DOES_NOT_APPLY
    exclusion_reason: We don't have sentencing information in NC. TODO(#56006) if we do ingest sentences!
max_allowed_error_overrides: []
num_allowed_rows_overrides:
  - validation_name: overlapping_supervision_periods
    hard_num_allowed_rows_override: 1
    override_reason: >-
      The periods really are overlapping the data, but it's so few that I don't want to
      worry about this yet. I think to fix this particular instance, I could remove rows
      which are deleted for only a few days for a given OPUS, since it's unlikely that
      someone would actually have been removed for such a short period of time.
